spring:
  application:
    name: service-turbine
server:
  port: 8766

turbine:
  app-config: 
  aggregator:
    cluster-config: default
  cluster-name-expression:  new String("default")

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

