eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
server:
  port: 8762
spring:
  application:
    name: service-hello

management:
  endpoints:
    web:
      exposure:
        include: '*'


#hystrix:
#  command:
#    default:
#      requestLog:
#        enable: false
#      execution:
#        isolation:
#          thread:
#            timeoutInMilliseconds: 2000
#
#          strategy: SEMAPHORE
#          semaphore:
#           maxConcurrentRequests: 3



